[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[functions.keepalive]
  schedule = "@daily"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
[functions."generate"]
  timeout = 26
